[tool.black]
line-length = 120
target-version = ['py310']
skip-string-normalization = true

[tool.flake8]
max-line-length = 120
exclude = [
    ".git",
    "__pycache__",
    "venv",
    "env",
    "migrations",
]
